from .alimento import Alimento
from .alimentoplato import AlimentoPlato
from .carrera import Carrera
from .categoria import Categoria
from .estudiante import Estudiante
from .estudianteseccion import EstudianteSeccion
from .grado import Grado
from .menu import Menu
from .menuplato import MenuPlato
from .menualimento import MenuAlimento
from .nutriente import Nutriente
from .nutrientealimento import NutrienteAlimento
from .plato import Plato
from .seccion import Seccion
from .servicio import Servicio
from .unidad import Unidad
