# Generated by Django 5.2.6 on 2025-09-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almuerzo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='lugar_de_residencia',
            field=models.CharField(default='AZUA', max_length=100),
        ),
    ]
