# Generated by Django 5.2.6 on 2025-09-23 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almuerzo', '0002_estudiante_lugar_de_residencia'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='estudianteseccion',
            unique_together={('estudiante', 'seccion')},
        ),
    ]
