# Generated by Django 5.2.6 on 2025-09-25 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almuerzo', '0003_alter_estudianteseccion_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstudianteSeccion',
        ),
    ]
