# Generated by Django 5.2.6 on 2025-09-25 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almuerzo', '0004_delete_estudianteseccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='seccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='almuerzo.seccion'),
            preserve_default=False,
        ),
    ]
