# Generated by Django 5.2.6 on 2025-09-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almuerzo', '0005_estudiante_seccion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicio',
            unique_together={('estudiante', 'fecha_servido')},
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='apellido',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='lugar_de_residencia',
            field=models.CharField(default='AZUA', max_length=50),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='notas',
        ),
    ]
