# Generated by Django 5.2.6 on 2025-09-25 15:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almuerzo', '0006_alter_servicio_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='fecha_creacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
