# Generated by Django 5.2.6 on 2025-09-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almuerzo', '0007_alter_menu_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='menualimento',
            name='gramos',
            field=models.FloatField(default=1, help_text='Cantidad usada en la receta (gramos)'),
            preserve_default=False,
        ),
    ]
