# Generated by Django 5.2.6 on 2025-09-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almuerzo', '0008_menualimento_gramos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AlterModelOptions(
            name='nutriente',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='menu',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
    ]
