# Generated by Django 5.2.6 on 2025-09-26 16:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almuerzo', '0009_alter_menu_options_alter_nutriente_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='fecha_creacion',
            field=models.DateField(default=django.utils.timezone.now, unique=True),
        ),
    ]
