# Generated by Django 5.2.6 on 2025-09-30 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almuerzo', '0010_alter_menu_fecha_creacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['-fecha_servido']},
        ),
    ]
